"""empty message

Revision ID: 0cf36ff15227
Revises: 3f577c7dc7f3
Create Date: 2025-06-19 01:35:39.956555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cf36ff15227'
down_revision = '3f577c7dc7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('book_tag_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('book_tag_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['tag_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('comment_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('待处理', '已处理'),
               type_=sa.Enum('待处理', '已受理已解决', name='complaint_status'),
               existing_nullable=False)

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('forum_post_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('forum_post_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_post_ibfk_2'), 'user', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('forum_post_ibfk_1'), 'book', ['book_id'], ['book_id'])

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('待处理', '已受理已解决', name='complaint_status'),
               type_=mysql.ENUM('待处理', '已处理'),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_3'), 'user', ['user_id'], ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('book_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('book_tag_ibfk_1'), 'book', ['book_id'], ['book_id'])
        batch_op.create_foreign_key(batch_op.f('book_tag_ibfk_2'), 'tag', ['tag_id'], ['tag_id'])

    # ### end Alembic commands ###
