"""fix version error

Revision ID: 324a552cc4ed
Revises: a3c84235acf4
Create Date: 2025-06-18 23:03:27.754065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '324a552cc4ed'
down_revision = 'a3c84235acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
