"""add image_url for book

Revision ID: 370388e9574e
Revises: 93be9dbc0643
Create Date: 2025-06-16 16:16:57.686714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370388e9574e'
down_revision = '93be9dbc0643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
