"""fix comment error

Revision ID: 3f577c7dc7f3
Revises: dfc902326c4f
Create Date: 2025-06-19 00:20:35.444534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f577c7dc7f3'
down_revision = 'dfc902326c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_comment_id'], ['comment_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_1'), 'comment', ['parent_comment_id'], ['comment_id'])

    # ### end Alembic commands ###
