"""Tag table | modify the book_tag table

Revision ID: 5e4af550f518
Revises: 370388e9574e
Create Date: 2025-06-16 20:54:18.390949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e4af550f518'
down_revision = '370388e9574e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('book_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['tag_id'])
        batch_op.drop_column('book_tag_id')
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('book_tag_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')

    op.drop_table('tag')
    # ### end Alembic commands ###
