"""empty message

Revision ID: 73c10fd387fe
Revises: 
Create Date: 2025-06-18 23:03:12.709601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c10fd387fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('default_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book_tag',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('complaint_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('待处理', '已受理', '已解决', name='complaint_status'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('forum_post',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.Column('browse_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('未支付', '已支付', '已发货', '已完成', '订单取消', name='order_status'), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('ship_time', sa.DateTime(), nullable=True),
    sa.Column('get_time', sa.DateTime(), nullable=True),
    sa.Column('ship_address', sa.String(length=255), nullable=True),
    sa.Column('bill_address', sa.String(length=255), nullable=False),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('shipper_phone', sa.String(length=20), nullable=True),
    sa.Column('biller_phone', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('suggestion',
    sa.Column('suggestion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggestion_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_table('user_browse',
    sa.Column('browse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('browse_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('browse_id')
    )
    op.create_table('user_cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('user_favorite',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('favorite_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('comment_time', sa.DateTime(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('order_detail',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('order_id', 'book_id', name='uix_order_book')
    )
    op.create_table('post_like',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('suggestion_agree',
    sa.Column('agree_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestion.suggestion_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('agree_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion_agree')
    op.drop_table('post_like')
    op.drop_table('order_detail')
    op.drop_table('comment')
    op.drop_table('user_favorite')
    op.drop_table('user_cart')
    op.drop_table('user_browse')
    op.drop_table('suggestion')
    op.drop_table('order')
    op.drop_table('forum_post')
    op.drop_table('complaint')
    op.drop_table('book_tag')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('book')
    op.drop_table('admin')
    # ### end Alembic commands ###
