"""add title and is_deleted to table forumpost

Revision ID: 93be9dbc0643
Revises: 8919aca06a70
Create Date: 2025-06-15 20:27:57.698463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93be9dbc0643'
down_revision = '8919aca06a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
