"""add trigger

Revision ID: a3c84235acf4
Revises: ecc328e2545d
Create Date: 2025-06-18 16:21:06.489743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c84235acf4'
down_revision = 'ecc328e2545d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_detail_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_detail_ibfk_3'), 'book', ['book_id'], ['book_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
