"""empty message

Revision ID: aa64aa67c253
Revises: b4fbc2d8d6bb
Create Date: 2025-06-14 16:32:25.904696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa64aa67c253'
down_revision = 'b4fbc2d8d6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tag',
    sa.Column('book_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('book_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_tag')
    # ### end Alembic commands ###
