"""modify the order and order detail table

Revision ID: c3ebba8d662b
Revises: 5e4af550f518
Create Date: 2025-06-17 14:41:52.960378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3ebba8d662b'
down_revision = '5e4af550f518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('ship_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('current_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('shipper_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_order_book', ['order_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_constraint('uix_order_book', type_='unique')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('shipper_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('current_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ship_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
