"""add cascade delete and set null

Revision ID: ecc328e2545d
Revises: 01b8e40b7339
Create Date: 2025-06-18 15:16:01.110594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc328e2545d'
down_revision = '01b8e40b7339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['admin_id'], ondelete='SET NULL')

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('order_detail_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='SET NULL')

    with op.batch_alter_table('user_browse', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_browse_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_browse_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_cart', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_cart_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_cart_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='SET NULL')

    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_favorite_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_favorite_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_favorite_ibfk_1'), 'book', ['book_id'], ['book_id'])
        batch_op.create_foreign_key(batch_op.f('user_favorite_ibfk_2'), 'user', ['user_id'], ['user_id'])
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_cart_ibfk_1'), 'book', ['book_id'], ['book_id'])
        batch_op.create_foreign_key(batch_op.f('user_cart_ibfk_2'), 'user', ['user_id'], ['user_id'])
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_browse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_browse_ibfk_1'), 'book', ['book_id'], ['book_id'])
        batch_op.create_foreign_key(batch_op.f('user_browse_ibfk_2'), 'user', ['user_id'], ['user_id'])
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_detail_ibfk_1'), 'book', ['book_id'], ['book_id'])
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_ibfk_1'), 'admin', ['admin_id'], ['admin_id'])

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
